import Foundation

func repeatedCharacter(_ s: String) -> Character {
    var characters = [Character]()
    
    for char in s {
        if characters.contains(char) {
            return char
        } else {
            characters.append(char)
        }
    }
    
    return " "
}
    


let startTime = Date()

repeatedCharacter("wlsqyxtrjyqrnqwxcbgjxwzvqnrjoljnkcpypnuwxinrqklpvuyzifszwvpalqjsvhbwbvqllhdpshdkhdywzvwdszsepxnhsavavfjpfzhjbechakgzqftkqowbjzgdwogkgyajuyfmxrvlqagunffpncjekpknjxljcnexepkytqwfvwvtrrgjhqlbywxkcyfycnrwpibuegbhpwsveanpmptxxzvvtuekjhozvfwyqzyaxnrwzldnfpmfmlnbwlalnskphxieqlelkzlekywgojlrfxmbxbrylzsbzrtoyrzwaytdwcahnurijmlydyimcbccnkbbzzvntosmwpifumrjzevzmldxnztdoqmzfmskhrwqaxubjyrdjeopmeukccnfngkxcodcxqnnjmcybllhqbcdwduqlvsbfpqcxaxwgjfhwdpycivdkokrsrvcukuhafncwlsqywxtrjyqrnqwxcbgjxwzvqnrjoljnkcpypnuwxinrqklpvuyzifszwvpalqjsvhbwbvqllhdpshdkhdywzvwdszsepxnhsavavfjpfzhjbechakgzqftkqowbjzgdwogkgyajuyfmxrvlqagunffpncjekpknjxljcnexepkytqwfvwvtrrgjhqlbywxkcyfycnrwpibuegbhpwsveanpmptxxzvvtuekjhozvfwyqzyaxnrwzldnfpmfmlnbwlalnskphxieqlelkzlekywgojlrfxmbxbrylzsbzrtoyrzwaytdwcahnurijmlydyimcbccnkbbzzvntosmwpifumrjzevzmldxnztdoqmzfmskhrwqaxubjyrdjeopmeukccnfngkxcodcxqnnjmcybllhqbcdwduqlvsbfpqcxaxwgjfhwdpycivdkokrsrvcukuhafxkcyfycnrwpibuegbhpwsveanpmptxxzvvtuekjhozvfwyqzyaxnrwzldnfpmfmlnbwlalnskphxieqlelkzlekywgojlrfxmbxbrylzsbzrtoyrzwaytdwcahnurijmlydyimcbccnkbbzzvntosmwpifumrjzevzmldxnztdoqmzfmskhrwqaxubjyrdjeopmeukccnfngkxcodcxqnnjmcybllhqbcdwduqlvsbfpqcxaxwgjfhwdpycivdkokrsrvcukuhafwlsqywxtrjyqrnqwxcbgjxwzvqnrjoljnkcpypnuwxinrqklpvuyzifszwvpalqjsvhbwbvqllhdpshdkhdywzvwdszsepxnhsavavfjpfzhjbechakgzqftkqowbjzgdwogkgyajuyfmxrvlqagunffpncjekpknjxljcnexepkytqwfvwvtrrgjhqlbywxkcyfycnrwpibuegbhpwsveanpmptxxzvvtuekjhozvfwyqzyaxnrwzldnfpmfmlnbwlalnskphxieqlelkzlekywgojlrfxmbxbrylzsbzrtoyrzwaytdwcahnurijmlydyimcbccnkbbzzvntosmwpifumrjzevzmldxnztdoqmzfmskhrwqaxubjyrdjeopmeukccnfngkxcodcxqnnjmcybllhqbcdwduqlvsbfpqcxaxwgjfhwdpycivdkokrsrvcukuhafncwlsqywxtrjyqrnqwxcbgjxwzvqnrjoljnkcpypnuwxinrqklpvuyzifszwvpalqjsvhbwbvqllhdpshdkhdywzvwdszsepxnhsavavfjpfzhjbechakgzqftkqowbjzgdwogkgyajuyfmxrvlqagunffpncjekpknjxljcnexepkytqwfvwvtrrgjhqlbywxkcyfycnrwpibuegbhpwsveanpmptxxzvvtuekjhozvfwyqzyaxnrwzldnfpmfmlnbwlalnskphxieqlelkzlekywgojlrfxmbxbrylzsbzrtoyrzwaytdwcahnurijmlydyimcbccnkbbzzvntosmwpifumrjzevzmldxnztdoqmzfmskhrwqaxubjyrdjeopmeukccnfngkxcodcxqnnjmcybllhqbcdwduqlvsbfpqcxaxwgjfhwdpycivdkokrsrvcukuhafxkcyfycnrwpibuegbhpwsveanpmptxxzvvtuekjhozvfwyqzyaxnrwzldnfpmfmlnbwlalnskphxieqlelkzlekywgojlrfxmbxbrylzsbzrtoyrzwaytdwcahnurijmlydyimcbccnkbbzzvntosmwpifumrjzevzmldxnztdoqmzfmskhrwqaxubjyrdjeopmeukccnfngkxcodcxqnnjmcybllhqbcdwduqlvsbfpqcxaxwgjfhwdpycivdkokrsrvcukuhaf")
for _ in 1...1000000 {
    // Example computation
    let result = 1 + 1
}

let endTime = Date()
let runtime = endTime.timeIntervalSince(startTime)
print("Runtime: \(runtime) seconds")
